//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consulta
    {
        public int idConsulta { get; set; }
        public int idEmpleado { get; set; }
        public string idPaciente { get; set; }
        public System.DateTime fecha { get; set; }
        public int costo { get; set; }
        public string motivo { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual paciente paciente { get; set; }
    }
}
