//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class receta
    {
        public int idReceta { get; set; }
        public int idPaciente { get; set; }
        public int idEmpleado { get; set; }
        public DateTime fechaReceta { get; set; }
        public string detalleReceta { get; set; }

        public virtual empleado empleado { get; set; }
        public virtual paciente paciente { get; set; }
       
    }
}
